/**
 * Data Service to retrieve movie datasets and pipeline run logs.
 * Supports both local JSON fallback and live Supabase queries if configured.
 */

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const fetchMoviesData = async () => {
    try {
        if (SUPABASE_URL && SUPABASE_KEY && !SUPABASE_URL.includes("your-supabase")) {
            const res = await fetch(`${SUPABASE_URL}/rest/v1/movies?select=*&order=quality_score.desc`, {
                headers: {
                    'apikey': SUPABASE_KEY,
                    'Authorization': `Bearer ${SUPABASE_KEY}`
                }
            });
            if (res.ok) {
                const data = await res.json();
                if (data && data.length > 0) return data;
            }
        }
    } catch (e) {
        console.warn("Supabase fetch failed, falling back to local dataset:", e);
    }

    // Fallback to static local dataset generated by pipeline
    try {
        const res = await fetch(`/data/movies.json?t=${Date.now()}`);
        if (!res.ok) throw new Error(`Local movies dataset not found (status ${res.status})`);
        const contentType = res.headers.get('content-type');
        if (contentType && contentType.includes('text/html')) {
            throw new Error("Received HTML rewrite response instead of JSON");
        }
        return await res.json();
    } catch (err) {
        console.error("Failed to load movies data:", err);
        return [];
    }
};

export const fetchPipelineRuns = async () => {
    try {
        if (SUPABASE_URL && SUPABASE_KEY && !SUPABASE_URL.includes("your-supabase")) {
            const res = await fetch(`${SUPABASE_URL}/rest/v1/pipeline_runs?select=*&order=timestamp.desc&limit=20`, {
                headers: {
                    'apikey': SUPABASE_KEY,
                    'Authorization': `Bearer ${SUPABASE_KEY}`
                }
            });
            if (res.ok) {
                const data = await res.json();
                if (data && data.length > 0) return data;
            }
        }
    } catch (e) {
        console.warn("Supabase pipeline runs fetch failed, falling back to local logs:", e);
    }

    try {
        const res = await fetch(`/data/pipeline_runs.json?t=${Date.now()}`);
        if (!res.ok) throw new Error(`Local pipeline runs log not found (status ${res.status})`);
        const contentType = res.headers.get('content-type');
        if (contentType && contentType.includes('text/html')) {
            throw new Error("Received HTML rewrite response instead of JSON");
        }
        return await res.json();
    } catch (err) {
        console.error("Failed to load pipeline runs:", err);
        return [];
    }
};
